Add definitions and references for constructors
sourcegraph/scip-typescript pull request #250
Opened 2023-04-24 19:29 UTC by SuperAuguste

Closes #249

### Test plan

Tested locally with a snapshot, still need to test edge cases + implement and test inherited constructors.

2023-04-25 09:03 UTC, olafurpg requested changes
Impressive first PR @SuperAuguste! This is definitely a tricky issue to fix and I see you've already become familiar with the tsc APIs 😄 

It's mostly just me who has worked in this codebase so far and there are many undocumented conventions and assumptions. Don't hesitate to push back if some of these comments are too nitpicky, I prefer to have more relaxed conventions if it makes it easier for more people to contribute (rather than strictly enforcing some undocumented style making it a drudge to contribute).

2023-04-25 09:03 UTC, olafurpg commented on src/FileIndexer.ts
> +    if (!this.sourceFile.fileName.includes('constructor')) {
Let's uncomment this and re-run the snapshots

2023-04-25 09:03 UTC, olafurpg commented on src/main.test.ts
> +  if (!snapshotDirectory.includes('syntax')) {
Also uncomment here

2023-04-25 09:03 UTC, olafurpg commented on src/FileIndexer.ts
> +        ts.isConstructorDeclaration(node)
Minor: it's probably about time to move this ternary into a separate function

2023-04-25 09:03 UTC, olafurpg commented on snapshots/input/syntax/src/constructor.ts
> +export function useConstructor(): Constructor {
Can we add a test case for this syntax `new a.A()`? We have examples of this in the codebase 

```
        new scip.scip.Occurrence({
          range,
          symbol: scipSymbol.value,
          symbol_roles: role,
        })
```

I think it's OK to assume `node.expression` will only be an identifier or member selection (can't remember what tsc calls it: `a.b` expressions).

2023-04-25 09:03 UTC, olafurpg commented on src/FileIndexer.ts
> +    if (
Nit: I'd prefer to move this logic into `getTSSymbolLocation` and `visitSymbolOccurrence` by looking at the parents to determine if the identifier is part of a new expression. We already emit an occurrence over the identifier, it's just the wrong symbol.

My undocumented goal with the `visit()` function is to have it as small as possible by exclusively performing the traversal.

2023-04-25 09:03 UTC, olafurpg commented on src/FileIndexer.ts
> +        for (const member of declaration.members) {
I think it's better to just do `ScipSymbol.global(classDeclarationSymbol, methodDescriptor("<constructor>"))` 🤔 It's probably not a performance issue for cases when the constructor is the first member of this list but it could become a performance issue when the constructor doesn't exist (for whatever reason) and we exhaustively iterate through a very large number of members (TypeScript types can become very big with union types!).

2023-04-25 09:03 UTC, olafurpg commented on src/FileIndexer.ts
> +      relationships.push(
Can you elaborate on the motivation for this relationship? My understanding is that it's redundant since we're already emitting a definition occurrence.

<img width="1101" alt="CleanShot 2023-04-25 at 10 55 06@2x" src="https://user-images.githubusercontent.com/1408093/234226468-0b95e296-88ea-4c43-b91e-ab16181a0165.png">

Definition relationships are only useful for symbols that are missing a definition occurrence.

2023-04-25 13:25 UTC, SuperAuguste commented on src/FileIndexer.ts
> +      relationships.push(
Oops thanks for letting me know 😅 I'll rewrite this

2023-04-25 14:19 UTC, SuperAuguste commented on src/FileIndexer.ts
> +        for (const member of declaration.members) {
This makes sense, but what if there's no constructor? Then we'd just be pointing to nothing which isn't the behavior we want :(

2023-04-25 14:52 UTC, SuperAuguste commented
CI failing due to different TypeScript versions :/

Not sure why it's not respecting the `^` directive in the `package.json` and just getting the oldest compatible version instead. I guess I can downgrade and regenerate.

2023-04-25 17:32 UTC, olafurpg requested changes
This PR is really shaping up! Only blocking comments are

- Add back your constructor detection logic, but with a cache
- Undo changes in yarn.lock, I suspect this might fix the failing CI

2023-04-25 17:32 UTC, olafurpg commented on snapshots/package.json
> +    "@sourcegraph/tsconfig": "4.0.1",
Was this change intentional?

2023-04-25 17:32 UTC, olafurpg commented on src/FileIndexer.ts
> +        for (const member of declaration.members) {
You're right! We need to fallback to the class if the constructor doesn't exist. We can add a minimized test case to reproduce it

```ts
export class NoConstructor {
  property: number
}

export function useNoConstructor() {
  return new NoConstructor()
}
```

We will need the original for loop to detect if the class has a constructor but I propose we cache the result in a `hasConstructor: Map<ScipSymbol, boolean>` that lives in `ProjectIndexer` (next to `symbolCache`). Without the cache we risk iterating through all the members on every new expression, and I can imagine pathological cases (for example, generated code) where this iteration could become expensive.

2023-04-25 17:48 UTC, SuperAuguste commented on snapshots/package.json
> +    "@sourcegraph/tsconfig": "4.0.1",
Uh running yarn install just changed the order of the packages, I don't think this affects behavior but yeah this wasn't intentional :(

2023-04-25 18:05 UTC, SuperAuguste commented
> Undo changes in yarn.lock, I suspect this might fix the failing CI

The current package.json seems to be invalid due to a peer resolution issue (I ran `yarn install --immutable --immutable-cache` to not modify the `yarn.lock`) so my install won't go through. How do you install the deps for this repo without modifying the package.json/lockfile? :)

2023-04-25 18:58 UTC, SuperAuguste commented
Figured out the issue - the yarn version used here is a few years behind it seems, so I installed v1.22.19 and everything worked out!

2023-04-26 10:28 UTC, olafurpg approved these changes
Glorious 😍 Thank you @SuperAuguste!

2023-04-26 10:28 UTC, olafurpg commented on Development.md
> +Please note that the yarn version used by CI is `v1.22.19` - you should use this version as well to prevent lockfile conflicts.
Followup https://github.com/sourcegraph/scip-typescript/issues/251

2023-04-26 10:28 UTC, olafurpg commented on snapshots/output/syntax/src/constructor.ts
> +    return new NoConstructor()
Nice! 🤩

2023-04-26 10:28 UTC, olafurpg commented on src/FileIndexer.ts
> -      const signatureDeclaration: ts.SignatureDeclaration | undefined =
I hadn't realized this was already inside a function 🤦🏻 The new code looks good though 👍🏻

2023-04-26 10:29 UTC, merged

2023-04-26 10:29 UTC, olafurpg commented
> . How do you install the deps for this repo without modifying the package.json/lockfile? :)


I normally run `yarn` without a subcommand